In [51]:
import os
from dotenv import load_dotenv

load_dotenv()

True

# 1 Data Collection #

In this project the data will come from NBA Stats API.

In [9]:
import requests
import pandas as pd

In [ ]:

api_url = os.getenv("API_URL")
teams_url = api_url + "teams"
api_key = os.getenv("API_KEY")

headers = {
	"x-rapidapi-key": f"{api_key}",
	"x-rapidapi-host": "api-nba-v1.p.rapidapi.com"
}

response = requests.get(teams_url, headers=headers)

In [28]:
data = response.json()
teams = response.json()["response"]
teams_Df = pd.DataFrame(teams)
teams_Df.head()

,id,name,nickname,code,city,logo,allStar,nbaFranchise,leagues
0,1,Atlanta Hawks,Hawks,ATL,Atlanta,https://upload.wikimedia.org/wikipedia/fr/e/ee...,False,True,"{'standard': {'conference': 'East', 'division'..."
1,2,Boston Celtics,Celtics,BOS,Boston,https://upload.wikimedia.org/wikipedia/fr/thum...,False,True,"{'standard': {'conference': 'East', 'division'..."
2,3,Brisbane Bullets,Bullets,BNE,Brisbane,https://upload.wikimedia.org/wikipedia/fr/thum...,False,False,"{'standard': {'conference': 'Intl', 'division'..."
3,4,Brooklyn Nets,Nets,BKN,Brooklyn,https://upload.wikimedia.org/wikipedia/commons...,False,True,"{'standard': {'conference': 'East', 'division'..."
4,5,Charlotte Hornets,Hornets,CHA,Charlotte,https://upload.wikimedia.org/wikipedia/fr/thum...,False,True,"{'standard': {'conference': 'East', 'division'..."

In [84]:
nbaTeams_Df = teams_Df[teams_Df['nbaFranchise']].reset_index(drop=True)
nbaTeams_Df.shape

(31, 9)

In [85]:
nbaTeams_Df["conference"] = nbaTeams_Df["leagues"].apply(lambda x: x["standard"]["conference"] if isinstance(x, dict) and "standard" in x else None)
nbaTeams_Df["division"] = nbaTeams_Df["leagues"].apply(lambda x: x["standard"]["division"] if isinstance(x, dict) and "standard" in x else None)

In [86]:
nbaTeams_Df = nbaTeams_Df.drop(columns=['allStar', 'leagues', 'nickname', 'code', 'logo', 'city', 'nbaFranchise'], axis=1)

nbaTeams_Df

    id                    name conference   division
0    1           Atlanta Hawks       East  Southeast
1    2          Boston Celtics       East   Atlantic
2    4           Brooklyn Nets       East   Atlantic
3    5       Charlotte Hornets       East  Southeast
4    6           Chicago Bulls       East    Central
5    7     Cleveland Cavaliers       East    Central
6    8        Dallas Mavericks       West  Southwest
7    9          Denver Nuggets       West  Northwest
8   10         Detroit Pistons       East    Central
9   11   Golden State Warriors       West    Pacific
10  14         Houston Rockets       West  Southwest
11  15          Indiana Pacers       East    Central
12  16             LA Clippers       West    Pacific
13  17      Los Angeles Lakers       West    Pacific
14  19       Memphis Grizzlies       West  Southwest
15  20              Miami Heat       East  Southeast
16  21         Milwaukee Bucks       East    Central
17  22  Minnesota Timberwolves       West  Northwest
18  23    New Orleans Pelicans       West  Southwest
19  24         New York Knicks       East   Atlantic
20  25   Oklahoma City Thunder       West  Northwest
21  26           Orlando Magic       East  Southeast
22  27      Philadelphia 76ers       East   Atlantic
23  28            Phoenix Suns       West    Pacific
24  29  Portland Trail Blazers       West  Northwest
25  30        Sacramento Kings       West    Pacific
26  31       San Antonio Spurs       West  Southwest
27  37     Home Team Stephen A       East       East
28  38         Toronto Raptors       East   Atlantic
29  40               Utah Jazz       West  Northwest
30  41      Washington Wizards       East  Southeast

In [50]:
nbaTeams_Df = nbaTeams_Df[nbaTeams_Df['name'] != 'Home Team Stephen A']
nbaTeams_Df.shape

(30, 4)

In [56]:
api_url = os.getenv("API_URL")
games_url = api_url + "games"
api_key = os.getenv("API_KEY")
querystring = {"season":"2021"}

headers = {
	"x-rapidapi-key": f"{api_key}",
	"x-rapidapi-host": "api-nba-v1.p.rapidapi.com"
}

response = requests.get(games_url, headers=headers, params=querystring)

In [103]:
data = response.json()
games = response.json()["response"]
games_Df = pd.DataFrame(games)
games_Df.head()

,id,league,season,date,stage,status,periods,arena,teams,scores,officials,timesTied,leadChanges,nugget
0,8787,standard,2021,"{'start': '2021-10-19T23:30:00.000Z', 'end': '...",2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Fiserv Forum', 'city': 'Milwaukee', ...","{'visitors': {'id': 4, 'name': 'Brooklyn Nets'...","{'visitors': {'win': 0, 'loss': 1, 'series': {...","[Josh Tiven, Natalie Sago, Jacyn Goble]",1.0,1.0,None
1,8788,standard,2021,"{'start': '2021-10-20T02:00:00.000Z', 'end': '...",2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'STAPLES Center', 'city': 'Los Angele...","{'visitors': {'id': 11, 'name': 'Golden State ...","{'visitors': {'win': 1, 'loss': 0, 'series': {...","[Sean Wright, Mark Lindsay, Ray Acosta]",5.0,7.0,None
2,8789,standard,2021,"{'start': '2021-10-20T23:00:00.000Z', 'end': '...",2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Spectrum Center', 'city': 'Charlotte...","{'visitors': {'id': 15, 'name': 'Indiana Pacer...","{'visitors': {'win': 0, 'loss': 1, 'series': {...","[Rodney Mott, Scott Wall, Nate Green]",7.0,9.0,None
3,8790,standard,2021,"{'start': '2021-10-20T23:00:00.000Z', 'end': '...",2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Little Caesars Arena', 'city': 'Detr...","{'visitors': {'id': 6, 'name': 'Chicago Bulls'...","{'visitors': {'win': 1, 'loss': 0, 'series': {...","[Derek Richardson, Tyler Ford, Mousa Dagher]",10.0,8.0,None
4,8791,standard,2021,"{'start': '2021-10-20T23:30:00.000Z', 'end': '...",2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 6, 'total': 4, 'endOfPeriod': False}","{'name': 'Madison Square Garden', 'city': 'New...","{'visitors': {'id': 2, 'name': 'Boston Celtics...","{'visitors': {'win': 0, 'loss': 1, 'series': {...","[Scott Foster, Ed Malloy, Lauren Holtkamp]",10.0,12.0,None

In [104]:
games_Df['stage'].unique()

array([2, 1, 3, 5, 4])

In [105]:
games_Df = games_Df[games_Df['stage'] != 1]
games_Df['stage'].unique()

array([2, 3, 5, 4])

In [106]:

games_Df['date'] = games_Df['date'].apply(lambda x: x['start'] if x['end'] else None)
games_Df.head()

,id,league,season,date,stage,status,periods,arena,teams,scores,officials,timesTied,leadChanges,nugget
0,8787,standard,2021,2021-10-19T23:30:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Fiserv Forum', 'city': 'Milwaukee', ...","{'visitors': {'id': 4, 'name': 'Brooklyn Nets'...","{'visitors': {'win': 0, 'loss': 1, 'series': {...","[Josh Tiven, Natalie Sago, Jacyn Goble]",1.0,1.0,None
1,8788,standard,2021,2021-10-20T02:00:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'STAPLES Center', 'city': 'Los Angele...","{'visitors': {'id': 11, 'name': 'Golden State ...","{'visitors': {'win': 1, 'loss': 0, 'series': {...","[Sean Wright, Mark Lindsay, Ray Acosta]",5.0,7.0,None
2,8789,standard,2021,2021-10-20T23:00:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Spectrum Center', 'city': 'Charlotte...","{'visitors': {'id': 15, 'name': 'Indiana Pacer...","{'visitors': {'win': 0, 'loss': 1, 'series': {...","[Rodney Mott, Scott Wall, Nate Green]",7.0,9.0,None
3,8790,standard,2021,2021-10-20T23:00:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Little Caesars Arena', 'city': 'Detr...","{'visitors': {'id': 6, 'name': 'Chicago Bulls'...","{'visitors': {'win': 1, 'loss': 0, 'series': {...","[Derek Richardson, Tyler Ford, Mousa Dagher]",10.0,8.0,None
4,8791,standard,2021,2021-10-20T23:30:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 6, 'total': 4, 'endOfPeriod': False}","{'name': 'Madison Square Garden', 'city': 'New...","{'visitors': {'id': 2, 'name': 'Boston Celtics...","{'visitors': {'win': 0, 'loss': 1, 'series': {...","[Scott Foster, Ed Malloy, Lauren Holtkamp]",10.0,12.0,None

In [107]:
games_Df = games_Df.sort_values('date').reset_index(drop=True)
games_Df

,id,league,season,date,stage,status,periods,arena,teams,scores,officials,timesTied,leadChanges,nugget
0,9553,vegas,2021,2021-08-17T19:00:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Thomas & Mack Center', 'city': 'Las ...","{'visitors': {'id': 8, 'name': 'Dallas Maveric...","{'visitors': {'win': 1, 'loss': 4, 'series': {...","[Biniam Maru, Omar Bermudez, Teresa Stuck]",NaN,NaN,None
1,9554,vegas,2021,2021-08-17T19:30:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Cox Pavilion', 'city': 'Las Vegas', ...","{'visitors': {'id': 40, 'name': 'Utah Jazz', '...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Matt Kallio, Greg Dandridge, Hortencia Sanche...",NaN,NaN,None
2,9555,vegas,2021,2021-08-17T21:00:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Thomas & Mack Center', 'city': 'Las ...","{'visitors': {'id': 14, 'name': 'Houston Rocke...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Brent Haskill, Jacob Barnett, Julian McFadden]",NaN,NaN,None
3,9556,vegas,2021,2021-08-17T21:30:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Cox Pavilion', 'city': 'Las Vegas', ...","{'visitors': {'id': 4, 'name': 'Brooklyn Nets'...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Angel Kent, Matt Rafferty, Ben Stirt]",NaN,NaN,None
4,9557,vegas,2021,2021-08-17T23:00:00.000Z,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Thomas & Mack Center', 'city': 'Las ...","{'visitors': {'id': 17, 'name': 'Los Angeles L...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Agon Abazi, J.D. Ralls, Josh Wilson]",NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1423,10941,standard,2021,None,4,"{'clock': None, 'halftime': False, 'short': 1,...","{'current': 0, 'total': 4, 'endOfPeriod': False}","{'name': 'FTX Arena', 'city': 'Miami', 'state'...","{'visitors': {'id': 27, 'name': 'Philadelphia ...","{'visitors': {'win': 51, 'loss': 31, 'series':...",[],NaN,NaN,None
1424,10955,standard,2021,None,4,"{'clock': None, 'halftime': False, 'short': 1,...","{'current': 0, 'total': 4, 'endOfPeriod': False}","{'name': 'FedExForum', 'city': 'Memphis', 'sta...","{'visitors': {'id': 11, 'name': 'Golden State ...","{'visitors': {'win': 53, 'loss': 29, 'series':...",[],NaN,NaN,None
1425,10968,standard,2021,None,4,"{'clock': None, 'halftime': False, 'short': 1,...","{'current': 0, 'total': 4, 'endOfPeriod': False}","{'name': 'American Airlines Center', 'city': '...","{'visitors': {'id': 11, 'name': 'Golden State ...","{'visitors': {'win': 53, 'loss': 29, 'series':...",[],NaN,NaN,None
1426,10969,standard,2021,None,4,"{'clock': None, 'halftime': False, 'short': 1,...","{'current': 0, 'total': 4, 'endOfPeriod': False}","{'name': 'Chase Center', 'city': 'San Francisc...","{'visitors': {'id': 8, 'name': 'Dallas Maveric...","{'visitors': {'win': 52, 'loss': 30, 'series':...",[],NaN,NaN,None
1427,10976,standard,2021,None,4,"{'clock': None, 'halftime': False, 'short': 1,...","{'current': 0, 'total': 4, 'endOfPeriod': False}","{'name': 'Chase Center', 'city': 'San Francisc...","{'visitors': {'id': 2, 'name': 'Boston Celtics...","{'visitors': {'win': 51, 'loss': 31, 'series':...",[],NaN,NaN,None

In [108]:
games_Df = games_Df[games_Df['date'] != None]

In [109]:
games_Df['date'] = pd.to_datetime(games_Df['date'])
games_Df.head()

,id,league,season,date,stage,status,periods,arena,teams,scores,officials,timesTied,leadChanges,nugget
0,9553,vegas,2021,2021-08-17 19:00:00+00:00,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Thomas & Mack Center', 'city': 'Las ...","{'visitors': {'id': 8, 'name': 'Dallas Maveric...","{'visitors': {'win': 1, 'loss': 4, 'series': {...","[Biniam Maru, Omar Bermudez, Teresa Stuck]",NaN,NaN,None
1,9554,vegas,2021,2021-08-17 19:30:00+00:00,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Cox Pavilion', 'city': 'Las Vegas', ...","{'visitors': {'id': 40, 'name': 'Utah Jazz', '...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Matt Kallio, Greg Dandridge, Hortencia Sanche...",NaN,NaN,None
2,9555,vegas,2021,2021-08-17 21:00:00+00:00,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Thomas & Mack Center', 'city': 'Las ...","{'visitors': {'id': 14, 'name': 'Houston Rocke...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Brent Haskill, Jacob Barnett, Julian McFadden]",NaN,NaN,None
3,9556,vegas,2021,2021-08-17 21:30:00+00:00,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Cox Pavilion', 'city': 'Las Vegas', ...","{'visitors': {'id': 4, 'name': 'Brooklyn Nets'...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Angel Kent, Matt Rafferty, Ben Stirt]",NaN,NaN,None
4,9557,vegas,2021,2021-08-17 23:00:00+00:00,2,"{'clock': None, 'halftime': False, 'short': 3,...","{'current': 4, 'total': 4, 'endOfPeriod': False}","{'name': 'Thomas & Mack Center', 'city': 'Las ...","{'visitors': {'id': 17, 'name': 'Los Angeles L...","{'visitors': {'win': 3, 'loss': 2, 'series': {...","[Agon Abazi, J.D. Ralls, Josh Wilson]",NaN,NaN,None